Repository mikedepetris/Gomoku-SDM, pull requests merged in 2023-01, with the labels that each got.

#64 Refactoring per rispettare principi Solid
  pom.xml
  src/main/java/it/units/gomokusdm/Board.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Stone.java
  src/test/java/it/units/gomokusdm/BoardTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
Labels: enhancement, help wanted

#70 Email screenshot by circleCI with failed build notification
  presentation/[Workflow] Failed- martat97-Gomoku-SDM on circleci-project-setup - workflowScreenshot 2023-01-17 151453.png
Labels: documentation

#97 Refactoring stampa della board
  build.gradle
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Utilities.java
  src/test/java/it/units/gomokusdm/UtilitiesTest.java
Labels: enhancement

#100 Refactoring per rimozione Code Smell : Message Chain in Board
  src/main/java/it/units/gomokusdm/Board.java
  src/test/java/it/units/gomokusdm/BoardTest.java
Labels: bug

#101 implementata verifica che i player abbiano nomi diversi #98
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/GameTest.java
  src/test/java/it/units/gomokusdm/PlayerTest.java
Labels: enhancement

#107 Scelta fra diverse dimensioni di board su cui giocare
  src/main/java/it/units/gomokusdm/Board.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/BoardTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
  src/test/java/it/units/gomokusdm/GameTest.java
Labels: enhancement

#115 Refactoring delle classi Board e Coordinates
  src/main/java/it/units/gomokusdm/Board.java
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Coordinates.java
  src/main/java/it/units/gomokusdm/Direction.java
  src/main/java/it/units/gomokusdm/GUI.java
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/BoardTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
  src/test/java/it/units/gomokusdm/CoordinatesTest.java
  src/test/java/it/units/gomokusdm/GameTest.java
Labels: enhancement

#122 120-lettura-da-file-esterno-di-configurazioni-di-gioco-per-i-test
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/test/java/it/units/gomokusdm/BoardTest.java
  src/test/java/it/units/gomokusdm/PlayerTest.java
Labels: enhancement

#124 fix dei test, da completare per CLI
  build.gradle
  src/main/java/it/units/gomokusdm/CLIController.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
Labels: bug

#134 71-estensione-copertura-dei-test
  build.gradle
  pom.xml
  src/main/java/it/units/gomokusdm/GUI.java
  src/test/java/it/units/gomokusdm/GUITest.java
  src/test/java/it/units/gomokusdm/GomokuSdmApplicationTests.java
Labels: enhancement

#131 Aggiunti test per BoardFormatter
  src/test/java/it/units/gomokusdm/BoardFormatterTest.java
Labels: enhancement

#137 refactoring_dopo_inspections
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/BoardTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
  src/test/java/it/units/gomokusdm/GameTest.java
Labels: enhancement

#138 fixed
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/Player.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
Labels: enhancement

#139 132-bug-non-dà-errore-se-scrivi-due-username-uguali
  build.gradle
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/GomokuSdmApplication.java
  src/main/java/it/units/gomokusdm/Utilities.java
  src/main/resources/logging.properties
Labels: bug, enhancement

#141 119-gestione-della-situazione-pareggio-tra-giocatori
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/GUI.java
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/GameTest.java
Labels: bug, enhancement

#144 Refactoring interfaccia Board e implementazione
  src/main/java/it/units/gomokusdm/Board.java
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/test/java/it/units/gomokusdm/BoardImplementationTest.java
Labels: enhancement

#150 Static Code Analysis
  build.gradle
  gradle.properties
  src/main/java/it/units/gomokusdm/BoardFormatter.java
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/GUI.java
  src/main/java/it/units/gomokusdm/Game.java
  src/main/java/it/units/gomokusdm/GomokuSdmApplication.java
  src/main/java/it/units/gomokusdm/Player.java
  src/main/java/it/units/gomokusdm/Stone.java
  src/main/java/it/units/gomokusdm/Utilities.java
  src/test/java/it/units/gomokusdm/BoardImplementationTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
  src/test/java/it/units/gomokusdm/GUITest.java
  src/test/java/it/units/gomokusdm/GameTest.java
  src/test/java/it/units/gomokusdm/UtilitiesTest.java
Labels: enhancement

#158 143-configurazione-del-log-per-filtrare-solo-gli-eventi-rilevanti
  src/main/java/it/units/gomokusdm/GUI.java
  src/main/java/it/units/gomokusdm/Game.java
  src/main/java/it/units/gomokusdm/GomokuSdmApplication.java
  src/main/java/it/units/gomokusdm/Utilities.java
  src/main/resources/logging.properties
  src/test/java/it/units/gomokusdm/GUITest.java
Labels: enhancement

#159 143-configurazione-del-log-per-filtrare-solo-gli-eventi-rilevanti
  src/main/java/it/units/gomokusdm/Game.java
Labels: bug

#163 156-gui-non-viene-effettuato-il-controllo-che-i-nomi-dei-giocatori-non-siano-uguali
  src/test/java/it/units/gomokusdm/GameTest.java
Labels: bug

#164 145-configurazione-di-log-e-printboard-per-recuperare-situazioni-di-gioco-da-usare-nei-test
  src/main/java/it/units/gomokusdm/BoardFormatter.java
  src/main/java/it/units/gomokusdm/CLIController.java
  src/main/java/it/units/gomokusdm/GUI.java
  src/main/java/it/units/gomokusdm/Game.java
  src/test/java/it/units/gomokusdm/BoardImplementationTest.java
  src/test/java/it/units/gomokusdm/CLIControllerTest.java
  src/test/resources/board_06.txt
Labels: enhancement

#168 166-estensione-dei-test-tramite-configurazioni-di-board-scritte-come-testi
  src/main/java/it/units/gomokusdm/BoardImplementation.java
  src/main/java/it/units/gomokusdm/Game.java
  src/main/java/it/units/gomokusdm/GomokuSdmApplication.java
  src/test/java/it/units/gomokusdm/BoardFormatterTest.java
  src/test/java/it/units/gomokusdm/BoardImplementationTest.java
  src/test/java/it/units/gomokusdm/GameTest.java
  src/test/resources/board_game_draw_60_stones.txt
Labels: enhancement

#170 169-gui-alertpopup-che-avvisa-se-i-nomi-dei-giocatori-sono-uguali
  src/main/java/it/units/gomokusdm/GUI.java
Labels: bug, enhancement

#171 151-gui-visualizzazione-numeri-di-mossa-sulle-pietre
  src/main/java/it/units/gomokusdm/GUI.java
Labels: enhancement

#183 162-gui-errore-nella-multipla-creazione-di-un-game
  src/main/java/it/units/gomokusdm/GUI.java
Labels: bug

#186 185-gui-da-settings-abilitare-o-disabilitare-il-numero-di-mossa-sulle-pietre
  src/main/java/it/units/gomokusdm/GUI.java
  src/test/java/it/units/gomokusdm/GUITest.java
Labels: enhancement
